version: '3.7'

services:

  db:
    image: postgres:12
    restart: always
    container_name: pstg-container-shop
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: shop